#!/bin/bash

if [ -f /etc/sysconfig/argo-voms-htpasswd ] ; then
 . /etc/sysconfig/argo-voms-htpasswd
else
 echo "/etc/sysconfig/argo-voms-htpasswd does not exist"
 exit 1
fi

# Defaults
HTPASSWD_CONFIG=${HTPASSWD_CONFIG:-"/etc/argo-voms-htpasswd/argo-voms-htpasswd.conf"}
HTPASSWD_OUTPUT=${HTPASSWD_OUTPUT:-"/etc/httpd/httpd.users"}
HTPASSWD_COPIES=${HTPASSWD_COPIES:-"/etc/nagios/htpasswd.users"}
/usr/libexec/argo-voms-htpasswd -c $HTPASSWD_CONFIG -o $HTPASSWD_OUTPUT

if [ $? = "0" ] ; then
   echo "OK"
   for COPY in $HTPASSWD_COPIES 
   do
      if [ -d `dirname $COPY` ] ; then
        cp -p $HTPASSWD_OUTPUT $COPY
      fi
   done
else
   exit $?
fi


